### ISSUE TITLE
Element Resize Detection.

### ISSUE THREAD

**Issue by yxqme** [Justineo/vue-echarts#100]
window变化才会重绘图表，节点变化不会重绘图表，比如一个经典场景，侧边导航可伸缩，此时内容区域是可变的，但是window并未变化

能否参考 [javascript-detect-element-resize](https://github.com/sdecima/javascript-detect-element-resize) 内置增加监测到父节点变化的时候重绘图表的配置呢？

**Comment by seminelee** [comment]
+1

**Comment by Dan0net** [comment]
The reason this happens is because the default CSS for the container `div` is:
```
.echarts {
 width: 600px;
 height: 400px;
}
```
Updating it to force `width: auto` allows the SVG is update to its parent element size correctly:
```
.echarts {
 width: auto;
}
```

**Comment by yxqme** [comment]
@Dan0net This produces a new bug, The chart part is blocked

**Comment by Justineo** [comment]
@Dan0net

Thanks but this is not related with this issue. Instead of `<svg>`, ECharts is using `<canvas>` for better performance for large datasets. This requires explicitly calling its `resize` method to re-render the chart when container size changes.

For Vue-ECharts, the `auto-resize` prop only attach resizing logic to window `resize` event. This issue is about auto-resizing whenever the size of the container DOM element change. Because this is not natively supported, we have to include a hacky element-resize-listener. I'm leaving this issue open because it might not be that good for performance.

**Comment by Dan0net** [comment]
Thanks @Justineo. Apologies for the confusion, I see it is `<canvas>` now. I see this is a slightly different problem I am replying to, however the fix above does address some cases of non-resizing (when parent elements change size on window resize). The default CSS seems to be a slightly unhelpful in this case.

**Comment by Justineo** [comment]
要监听元素尺寸变化，会潜在改变元素的 `position` 样式，还可能改变其内部的 DOM 结构。同时比如较为完备的项目如 `element-resize-detector` 打包后也有近 20K 的体积。Vue-ECharts 不准备直接引入这样的功能。如果自行评估后确认需要使用请自行引入。
